<?php include 'header.php' ?>

<div class="about">
  <p>WHAT IS MY DEAD DOG’S BIRTHDAY?</p>

  <p>
    MY DEAD DOG’S BIRTHDAY IS A VIRTUAL D.I.Y. SPACE THAT WAS BUILT WITH THE
    NOTION THAT THE ART WORLD SHOULD BE ACCESSIBLE, INCLUSIVE, INTERACTIVE AND
    FUN.
  </p>

  <p>
    WHAT’S WITH THE NAME?
  </p>

  <p>
    THE NAME IS ESSENTIALLY A COMMENTARY ON HOW PEOPLE USE SOCIAL MEDIA IN THE 21ST CENTURY.
  </p>

  <p>
    HOW DOES IT WORK?
  </p>

  <p>
    WE HOST MONTHLY SHOWS THAT ARE CURATED TO EXIST ON A VIRTUAL PLATFORM AND COMMUNICATE
    DIRECTLY ABOUT ART MAKING & NUANCED SOCIAL INTERACTION ONLINE IN THE 21ST CENTURY.
  </p>

  <p>
    HOW CAN I PARTICIPATE?
  </p>

  <p>
    SUBMIT TO OUR MONTHLY OPEN CALLS OR SEND IN A
    CURATORIAL PROPOSAL FORM TO OUR EMAIL AT
    DEADDOGSBIRTHDAY@GMAIL.COM
  </p>
</div>


<?php include 'footer.php' ?>
