<?php include 'header.php' ?>
<div class="show-in-progress">
  <p>OPEN CALL OCTOBER 2017 <br>
    I KNEW YOU BEFORE I MET YOU <br>
    CURATED BY JESSICA PETRYLAK <br>
  </p>

  <p>THE SOCIAL MEDIA PLATFORM APPS ARE PROGRESSIVELY CRAFTING A NEW WAY OF
    COMMUNICATING OUR IDEAS AND INNER SELF. THE PROJECTION OF IMAGES AND
    CONCEPTS CAN REACH AROUND THE WORLD QUICKLY AND WITH EASE. FOR THE ARTIST,
    MODERN-DAY INVOLVEMENT IN SOCIAL NETWORKING AND MEDIA COMMUNICATION
    REVITALIZES AND RENEWS THE EXPERIENCE OF INTERCONNECTING, SHARING AND MAKING
    ART. THERE ARE MANY QUESTIONS BROUGHT UP ABOUT DIARISTIC OVERSHARING, THE
    LEGITIMACY OF ART MADE ONLY FOR INTERNET VIEWING, AND HOW THE DIGITAL
    CONTENT WILL BE DISPLAYED/SOLD IN A TRADITIONAL GALLERY SETTING.
  </p>

  <p>
    GUIDELINES:<br>
    PLEASE SUBMIT UP TO (3) WORKS OF ANY MEDIUM - MADE FROM, FOR, OR INFLUENCED
    BY THE DIGITAL REALM TO DEADDOGSBIRTHDAY@GMAIL.COM  - QUALITY ON THE CONTENT
    MUST BE HIGH IN ORDER TO DISPLAY PROPERLY ON OUR WEBSITE. IF CHOSEN YOU WILL
    BE EXPECTED TO WRITE AN ARTIST STATEMENT.
  </p>

  <p>
    MY DEAD DOG’S BIRTHDAY PROHIBITS ANY DISTRIBUTION OF THE IMAGES DISPLAYED
    ON OUR SITE. WE HAVE DONE EVERYTHING WE CAN TO MAKE SURE THAT YOUR ARTWORK
    IS SAFE. ONCE UP ON OUR SITE WE ARE NOT RESPONSIBLE FOR ANY SCREENSHOTS OR
    DOWNLOADS OF YOUR IMAGE. PLEASE PROCEED WITH THIS KNOWLEDGE.
  </p>
</div>

<?php include 'footer.php' ?>
